### PR TITLE
lcb: #331 crash during varrisc

### LINKED ISSUE #331: lcb: Crash when trying to generate a compiler for the current VarRisc spec
When trying to generate an lcb for the current VarRisc spec with the following command `nativevadl lcb ABI.vadl` the lcb crashes with the following message:
```
2:49:37.264 [main] INFO  vadl.dump.HtmlDumpPass - HTML dump of phase 'Exception During SetMissingConfigurationValuesPass' at file:///Users/andi/Documents/openvadl/sys/v-risc/outputdump/0_Exception_During_SetMissingConfigurationValuesPass.html
                             ___ ___    _   ___ _  _
                            / __| _ \  /_\ / __| || |
                           | (__|   / / _ \\__ \ __ |
                            \___|_|_\/_/ \_\___/_||_|

                       🔥 The OpenVADL compiler crashed 🔥

This shouldn't have happened, please open an issue with the stacktrace below at:
https://github.com/OpenVADL/open-vadl/issues/new


Before the crash, the following dumps were generated:
	- output/dump/0_Exception_During_SetMissingConfigurationValuesPass.html

java.util.NoSuchElementException: No value present
	at java.base@21.0.4/java.util.Optional.orElseThrow(Optional.java:377)
	at vadl.gcb.passes.SetMissingConfigurationValuesPass.execute(SetMissingConfigurationValuesPass.java:51)
	at vadl.pass.PassManager.execPass(PassManager.java:170)
	at vadl.pass.PassManager.run(PassManager.java:153)
	at vadl.pass.PassManager.run(PassManager.java:119)
	at vadl.cli.BaseCommand.call(BaseCommand.java:309)
	at vadl.cli.BaseCommand.call(BaseCommand.java:62)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at vadl.cli.Main.main(Main.java:44)
	at java.base@21.0.4/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

### PR DESCRIPTION
**Pull request by kper**
This PR contains some fixes to improve the errors for varrisc. First and foremost, the ABI file didn't have an ISA. It was imported but not used, so the LCB crashed. Now, there is an improved error message for that.

After that, it still crashed without an error. That's why I added some additional error messages to spot the error.
The current error is 

```
error: Not supportedEXECUTING [51s]
     ╭──[sys/v-risc/VarRisc.vadl:74:7]
     │
  74 │     , rs1     = func5                    // source register index rs1
     │       ^^^^^^^^^^^^^^^
     │
```

I suspect that this is an "correct" error in the specification. In my opinion, it needs to be fixed.

Closes #331

### CODE REVIEW

File: vadl/main/vadl/gcb/passes/MachineInstructionLabelGroup.java [hunk 1]
```diff
@@ -79,6 +80,9 @@ public final Set<MachineInstructionLabel> labels() {
       return asCheapAsMoveCandidates;
     }
 
-    throw new ViamError("not supported");
+    throw Diagnostic.error(
+            "not supported to convert machine instruction label group to a set of "
```
Comment (Jozott00) [inline vadl/main/vadl/gcb/passes/MachineInstructionLabelGroup.java:84]: Error messages usually begin with a capital letter.

File: vadl/main/vadl/lcb/codegen/assembly/ParserGenerator.java [hunk 2]
```diff
@@ -124,7 +125,7 @@ public static String mapToName(ExpressionNode x) {
       return "";
     }
 
-    throw new ViamError("not supported");
+    throw Diagnostic.error("not supported expression for parser generator", x.location()).build();
```
Comment (Jozott00) [inline vadl/main/vadl/lcb/codegen/assembly/ParserGenerator.java:128]: Same here

**Review by Jozott00 — CHANGES_REQUESTED** [review]
