### PR TITLE
ast: Fixed error message when pseudo instruction was not found

### LINKED ISSUE #165: frontend: crash in ABI
The following spec gives the crash below:
```
instruction set architecture ISA = {
  register file X: Bits<5> -> Bits<32>
  memory   A: Bits<32> -> Bits<8>
}

application binary interface ABI for ISA = {
  alias register ra = X(0)
  alias register gp = X(1)
  alias register sp = X(2)
  alias register t0 = X(31)
  callee saved = [ra]
  caller saved = t0
  global pointer = gp
  stack  pointer = sp
  frame  pointer = sp
  return address = ra
  return value = ra
  function argument = t0

  pseudo absolute address load instruction = LA
  pseudo call instruction = CALL
  pseudo return instruction = RET

}

micro processor CPU implements ISA with ABI = {
  start = 0
  firmware = {
    A(0) := 0x1
   }
}
```
```
                            / __| _ \  /_\ / __| || |
                           | (__|   / / _ \\__ \ __ |
                            \___|_|_\/_/ \_\___/_||_|

                         🔥 The vadl compiler crashed 🔥

This shouldn't have happened, please open an issue with the stacktrace below at:
https://github.com/OpenVADL/open-vadl/issues/new


java.util.NoSuchElementException: No value present
	at java.base@21.0.4/java.util.Optional.orElseThrow(Optional.java:377)
	at vadl.ast.ViamLowering.visit(ViamLowering.java:373)
	at vadl.ast.ViamLowering.visit(ViamLowering.java:97)
	at vadl.ast.ApplicationBinaryInterfaceDefinition.accept(Definition.java:3314)
	at vadl.ast.ViamLowering.fetch(ViamLowering.java:153)
	at java.base@21.0.4/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base@21.0.4/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base@21.0.4/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base@21.0.4/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base@21.0.4/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base@21.0.4/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@21.0.4/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at vadl.ast.ViamLowering.generate(ViamLowering.java:135)
	at vadl.cli.BaseCommand.parseToVIAM(BaseCommand.java:222)
	at vadl.cli.BaseCommand.call(BaseCommand.java:287)
	at vadl.cli.BaseCommand.call(BaseCommand.java:61)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at vadl.cli.Main.main(Main.java:44)
	at java.base@21.0.4/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

### PR DESCRIPTION
**Pull request by kper**
Fixes #165

The new error message is

```
> Task :vadl-cli:run FAILED
error: Cannot find the pseudo return instruction
     ╭──[test.vadl:6:1]
     │
   6 │> application binary interface ABI for ISA = {
   7 │>   alias register ra = X(0)
   8 │>   alias register gp = X(1)
    ⋮  13 lines omitted here...
  22 │>   pseudo return instruction = RET
  23 │>
  24 │> }
     │
     │
     help: Maybe check if this instruction really exists or was spelled incorrectly?
```

### CODE REVIEW

**Comment by kper** [comment]
Are there any tests to check the generated diagnostics? @flofriday

File: vadl/main/vadl/ast/ViamLowering.java [hunk 1]
```diff
@@ -99,6 +99,9 @@ public class ViamLowering implements DefinitionVisitor<Optional<vadl.viam.Defini
 
   private static final String RELATIVE = "relative";
   private static final String GLOBAL_OFFSET_TABLE = "globalOffset";
+  private static final String
```
Comment (flofriday) [inline vadl/main/vadl/ast/ViamLowering.java:102]: **thought:** I don't think it's necessary to add a variable for each error message.

Comment (flofriday) [reply vadl/main/vadl/ast/ViamLowering.java:103]: I see what you mean but, that's not a pattern that isn't really established here and I don't think the two usages justify it right now, and we can always add it if it really will be used a lot.
But at that point we should probably refactor it to also do it with other messages. 🤔

**Review by flofriday — APPROVED** [review]

**Review by flofriday — APPROVED** [review]
